import { type ISODate, formatDate, relativeDays } from './dates.ts';
import { formatMoney } from './money.ts';
import {
  type Subscription,
  type Upcoming,
  DEFAULT_AUDIT,
  annualCost,
  audit,
  monthlyCost,
  nextRenewal,
  totals,
} from './subscriptions.ts';

const esc = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

/** Markdown summary used by the "Copy report" button and the Action's job summary. */
export function subscriptionReport(subs: readonly Subscription[], currency: string, on: ISODate): string {
  const money = (m: number) => formatMoney(m, currency, { locale: 'en-US' });
  const t = totals(subs);
  const rows = [...subs]
    .sort((a, b) => nextRenewal(a, on).localeCompare(nextRenewal(b, on)))
    .map((s) => {
      const next = nextRenewal(s, on);
      const flags = audit(s, on, DEFAULT_AUDIT).map((f) => f.label).join(', ') || '—';
      const status = s.status === 'paused' ? 'paused' : s.status === 'trial' ? `trial → ${s.trialEnds ?? '?'}` : 'active';
      return `| ${esc(s.name)} | ${esc(s.category)} | ${money(s.amount)} / ${s.cycle} | ${money(monthlyCost(s))} | \`${next}\` | ${status} | ${flags} |`;
    });

  return [
    `# Subscriptions`,
    ``,
    `**${money(t.monthly)}/month** · **${money(t.annual)}/year** across ${t.count} active services.`,
    ``,
    `| Service | Category | Price | Monthly | Next renewal | Status | Flags |`,
    `| :-- | :-- | --: | --: | :-- | :-- | :-- |`,
    ...rows,
    ``,
    `<sub>Generated by Tally on ${on}.</sub>`,
    ``,
  ].join('\n');
}

export function alertIssue(
  u: Upcoming,
  currency: string,
  opts: { redact?: boolean } = {},
): { title: string; body: string; key: string } {
  const money = (m: number) => formatMoney(m, currency, { locale: 'en-US' });
  const isTrial = u.sub.status === 'trial' && u.sub.trialEnds === u.date;
  const what = isTrial ? 'Trial ends' : 'Renews';
  const key = `tally:${u.sub.id}:${u.date}`;
  if (opts.redact) {
    // Encrypted repos: say *when*, not *what*. Details stay in the app.
    return {
      key,
      title: `${isTrial ? 'A free trial ends' : 'A subscription renews'} ${relativeDays(u.daysAway)}`,
      body: [
        `Something in your encrypted Tally file ${isTrial ? 'ends its trial' : 'renews'} on **${formatDate(u.date, 'en-US', { weekday: 'long', year: 'numeric' })}**.`,
        ``,
        `Open Tally to see which one. Details are hidden because the file is encrypted (set the \`TALLY_REDACT\` variable to \`0\` to show them).`,
        ``,
        `<!-- ${key} -->`,
      ].join('\n'),
    };
  }
  const title = `${what} ${relativeDays(u.daysAway)}: ${u.sub.name} (${money(u.sub.amount)})`;
  const body = [
    `**${u.sub.name}** ${what.toLowerCase()} on **${formatDate(u.date, 'en-US', { weekday: 'long', year: 'numeric' })}**.`,
    ``,
    `| | |`,
    `| :-- | :-- |`,
    `| Charge | ${money(u.sub.amount)} (${u.sub.cycle}) |`,
    `| Yearly cost | ${money(annualCost(u.sub))} |`,
    `| Category | ${esc(u.sub.category)} |`,
    u.sub.url ? `| Manage | ${u.sub.url} |` : null,
    ``,
    `Keep it? Close this issue. Cancelling? Do it before the date above, then set it to *paused* in Tally.`,
    ``,
    `<!-- ${key} -->`,
  ]
    .filter((l) => l !== null)
    .join('\n');
  return { title, body, key };
}
